from enum import StrEnum

class ReasonCode(StrEnum):
    CLEAN = "CLEAN"
    TARGET_LEAKAGE = "TARGET_LEAKAGE"
    INCOMPLETE_LINEAGE = "INCOMPLETE_LINEAGE"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    EVALUATION_UNAVAILABLE = "EVALUATION_UNAVAILABLE"
    POLICY_CONFIGURATION_ERROR = "POLICY_CONFIGURATION_ERROR"

class Verdict(StrEnum):
    APPROVED = "approved"
    BLOCKED = "blocked"
